security:
  basic:
    enabled: false

management:
  security:
    enabled: false

logging:
  level:
    io:
      pivotal: DEBUG
spring: # <---NEW SECTION
  cloud:
    services:
      registrationMethod: direct
spring:
  sleuth:
    sampler:
      percentage: 1.0
